version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9002:9002" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hungtran
      MONGO_INITDB_ROOT_PASSWORD: duyhungtran14022002

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hungtran
      ME_CONFIG_MONGODB_ADMINPASSWORD: duyhungtran14022002
      ME_CONFIG_MONGODB_URL: mongodb://hungtran:duyhungtran14022002@mongo:27017/
  mqtt-backend:
    container_name: mqtt-backend
    image: "hungtranit14/mqtt-backend"
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MQTT_SERVER: mqtt5
      MQTT_PORT: 1883
      MQTT_USERNAME: hungtran
      MQTT_PASSWORD: hungtran
      MONGODB_URL: mongodb://hungtran:duyhungtran14022002@mongo:27017/
    volumes:
      # So that Traefik can listen to the Docker events
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  config:
  data:
  log:
networks:
  default:
    name: mqtt5-network
